### ISSUE TITLE
New location of /convert/oxygen.py?

### ISSUE THREAD

**Issue by hhourston** [cioos-siooc/ocean-data-parser#102]
Hello,

I have some code from 2023 that imports the oxygen conversion function `O2stoO2c` from ocean_data_parser.convert.oxygen. In the version of ocean-data-parser that I just installed, the convert folder is gone. I'm wondering where the oxygen.py script has been moved to, or if it was removed.

Thanks,
Hana

**Comment by JessyBarrette** [comment]
Yes sorry for the issue encountered. Since the ocean-data-parser focus is on parsing manufacturer proprietary format the `convert` associated modules were removed from the present package. 

The oxygen module was move to it's own dedicated module:
https://github.com/HakaiInstitute/python-o2-conversion

Let me know if I can help for anything.

**Comment by hhourston** [comment]
Thanks, Jessy - I'll close this ticket.
